rtx.resolvePreCombinedMatrices = True
DXVK_REMIX_PREWARM=1
DXVK_REMIX_ENABLE_NRC=1
rtx.enableFirstBounceLobeProbabilityDithering = False
rtx.di.stealBoundaryPixelSamplesWhenOutsideOfScreen = False
rtx.dlssPreset = 2
rtx.qualityDLSS = 0
rtx.enableReplacementLights = True
rtx.enableReplacementAssets = False
rtx.minOpaqueSpecularLobeSamplingProbability = 0.05
rtx.taauPreset = 1
rtx.resolutionScale = 0.75
rtx.russianRoulette1stBounceMinContinueProbability = 0.8
rtx.enableReplacementMeshes = True
rtx.defaultToAdvancedUI = True
rtx.gui.textureGridThumbnailScale = 1
rtx.pathMinBounces = 1
rtx.neuralRadianceCache.trainingMaxPathBounces = 9
rtx.di.spatialSamples = 2
rtx.di.initialSampleCount = 3
rtx.integrateIndirectMode = 1
rtx.pathMaxBounces = 6
rtx.nisPreset = 1
rtx.neuralRadianceCache.terminationHeuristicThreshold = 0.1
rtx.postFilterThreshold = 10
rtx.neuralRadianceCache.smallestResolvableFeatureSizeMeters = 0.01
rtx.neuralRadianceCache.targetNumTrainingIterations = 4
rtx.xess.preset = 1
rtx.russianRouletteMode = 1
rtx.renderPassIntegrateIndirectRaytraceMode = 0
rtx.di.enableDenoiserConfidence = False
rtx.di.disocclusionSamples = 2
rtx.di.permutationSamplingNthFrame = 1
rtx.di.enableBestLightSampling = False
rtx.enableRayReconstruction = True
rtx.restoreCursorPosition = False
rtx.reflexMode = 1
rtx.demodulate.enableDirectLightBoilingFilter = False
rtx.graphicsPreset = 4
rtx.restirGI.useReflectionReprojection = True
rtx.enableReplacementMaterials = True
rtx.renderPassIntegrateDirectRaytraceMode = 0
rtx.upscalerType = 1
rtx.usePostFilter = False
rtx.di.enableSampleStealing = False
rtx.minOpaqueDiffuseLobeSamplingProbability = 0.05
rtx.neeCache.enableModeAfterFirstBounce = 2
rtx.renderPassGBufferRaytraceMode = 0
rtx.blockInputToGameInUI = True
rtx.showUICursor = True