// Generated by scripts/embed_fast_noise.py - DO NOT EDIT
//
// Embedded data: 128x128x32 RG8 noise vendored from EA's
// importance-sampled-FAST-noise repository:
// https://github.com/electronicarts/importance-sampled-FAST-noise
//
// Copyright (c) 2025 Electronic Arts Inc. All rights reserved.
// Used under the BSD-3-Clause-variant license in
// data/ea-fast-noise/LICENSE.txt.
#pragma once
#include <cstdint>

namespace dxvk {
namespace rtxFastNoise {
  constexpr uint32_t kWidth    = 128;
  constexpr uint32_t kHeight   = 128;
  constexpr uint32_t kSlices   = 32;
  constexpr uint32_t kChannels = 2;
  constexpr size_t   kDataSize = kWidth * kHeight * kSlices * kChannels;
  extern const uint8_t kData[kDataSize];
}
}
